#!/bin/bash

# This scripts require pipewire , 
# pipewire-pulse(void-linux : this package is included in pipewire), 
# pulseaudio -- not necessary but good for backup 

function check_pw {

    pwloc=$(whereis "pipewire" | awk "{print $2}")
    pwpulse=$(whereis "pipewire-pulse" | awk "{print $2}")

    if [[ -z "$pwloc" ]];then
       echo "Cannot find pipwire! Please set it up!" 
    elif [[ -z "$pwpulse" ]];then
       echo "Cannot find pipwire-pulse lib! Missing dependency!" 
    fi

}



#pipewire &
retry=20
$(pgrep pipwire)
#keep this that way
#running=($(pgrep pipewire))
running=($(pgrep pipewire))

function run_pipe { 

    function retry {
        counter=0 
        command=$1
        max_retry=20
        if [[ -n $2 ]];then
            max_retry=$2 
        fi
        echo "Retrying for $max_retry times!" 
        while [[ $counter -lt $max_retry ]] 
        do
            eval $command && break
            counter=$(($counter + 1))
        done
    }
    ppa_run=($(pgrep pipewire-pulse))
    echo ${#ppa_run[@]} 
    if [ ${#running[@]} -gt 0 ];then
        echo -e "pipewire is running under proc:"
        echo "${running[@]}"

        echo -e "pipewire-pulse is running under proc:"
        echo  "${ppa_run[@]}"

        if [[ ${#ppa_run[@]} -le 0 ]];then
            retry "pipewire-pulse" 10
        else 
            echo "Setup Completed!"
            return
        fi
        echo "failed to start pipewire-pulse"
        exit 
    else 
        #retry 10 time
        retry "pipewire" 10
        echo "Failed to start pipewire!"
        return
    fi
    # force to stop 
    exit
    
}

check_pw
run_pipe

pactl info | grep -i "pipewire"
pactl info | grep -i "server string"
#| grep -i pipewire

#pipewire-pulse
#== System pipewire ==
#!/bin/sh
#mkdir -p /run/pipewire
#umask 000
#PIPEWIRE_RUNTIME_DIR=/run/pipewire pipewire
#
##!/bin/execlineb -P
#foreground { mkdir -p /run/pipewire }
#fdmove -c 2 1
#s6-env PIPEWIRE_RUNTIME_DIR=/run/pipewire execline-umask 000 pipewire
#
#== System pipewire-pulse
##!/bin/sh
#mkdir -p /run/pulse
#umask 000
#PULSE_RUNTIME_PATH=/run pipewire-pulse
#
##!/bin/execlineb -P
#foreground { mkdir -p /run/pulse }
#fdmove -c 2 1
##s6-env PULSE_RUNTIME_PATH=/run execline-umask 000 pipewire-pulse


