#!/bin/bash

# script from fuzzpak
#!/usr/bin/env bash
#GPLv3

export $(dbus-launch)
DIR=${DIR:-$HOME/.var/app}
CMD=${CMD:-flatpak run}

launch_app() {
    result=$(find "${DIR}" -mindepth 1 -maxdepth 1 \
        -type d -iname "*$1*" -printf '%f\n')
    echo -e "The result : $result"
    flatpak run  $result
    # | xargs $CMD
}

# parse opts
while [ True ]; do
if [ "$1" = "--help" -o "$1" = "-h" ]; then
    echo " "
    echo "$0 [OPTIONS]"
    echo "--directory, -d   Location of flatpaks (default: $HOME/.var/app"
    echo " "
    exit
elif [ "$1" = "--directory" -o "$1" = "-d" ]; then
    DIR=$DIR
    shift 2
else
    break
fi
done

if [ -z "${1}" ]; then
    #echo "HERE all the avialable apps : "
    flatpak list --columns name
    #read -p "Choose"
    read -p "HERE all the avialable apps : " ans
    echo "Start Running $ans !!!"

    launch_app $ans
    exit 0
fi

